{{- $service := .Values.redis.fullnameOverride }}
{{- $port := .Values.redis.redis.port | default 6379 }}
{{- if gt (int .Values.service.replicas) 1 }}
{{- $service = printf "%s-haproxy" $service }}
{{- $port = .Values.redis.haproxy.servicePort | default 6379 }}
{{- end }}
apiVersion: arcana.helmetica.io/v1
kind: Arcanum
metadata:
  name: credentials
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  target:
    name: {{ .Values.credentials.targetSecret | default (printf "%s-credentials" .Release.Name) | quote }}
  credentials:
    valueMapping:
      REDIS_HOST:
        source: template
        value: {{ printf "%s.{{.InstanceNamespace}}.svc.cluster.local" $service | quote }}
      REDIS_PORT:
        source: const
        value: {{ $port | quote }}
      REDIS_USERNAME:
        source: const
        value: "default"
      REDIS_PASSWORD:
        source: objectRef
        kind: Secret
        name: {{ printf "%s-auth" .Release.Name | quote }}
        key: {{ .Values.redis.authKey | quote }}
      REDIS_URL:
        source: template
        value: {{ `redis://{{.REDIS_USERNAME}}:{{.REDIS_PASSWORD}}@{{.REDIS_HOST}}:{{.REDIS_PORT}}` | quote }}
      {{- /*
        Only for replica 3!
      */}}
      {{- if gt (int .Values.service.replicas) 1 }}
      REDIS_SENTINEL_HOST:
        source: template
        value: {{ printf "%s.{{.InstanceNamespace}}.svc.cluster.local" .Values.redis.fullnameOverride | quote }}
      REDIS_SENTINEL_PORT:
        source: const
        value: {{ .Values.redis.sentinel.port | default 26379 | quote }}
      REDIS_MASTER_GROUP_NAME:
        source: const
        value: {{ .Values.redis.redis.masterGroupName | default "mymaster" | quote }}
      {{- end }}
